# ReAct 思考鏈範例配置
# 提供完整的思考過程範例，幫助 AI 學習正確的工作流程

react_examples:
  - title: "搜尋型查詢示範 - 環境監控類"
    query: "我想知道 {TARGET_DEVICE} 這台設備的溫度狀況"
    steps:
      - type: "thought"
        content: "使用者想要查詢設備溫度，但我不確定具體應該使用哪個 show 指令來獲取溫度資訊。根據 workflow，我應該先使用 CiscoCommandSearch 搜尋正確的指令。"
      - type: "action"
        action: "CiscoCommandSearch"
        input: "cisco device temperature monitoring command"
      - type: "observation"
        content: "搜尋結果顯示可以使用 `show environment all` 或 `show environment temperature` 來查看設備溫度狀態。"
      - type: "thought"
        content: "很好，我已經找到了適合的指令。現在我可以使用 BatchCommandRunner 在指定設備上執行 `show environment all` 來獲取完整的環境資訊。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "{TARGET_DEVICE}: show environment all"
      - type: "observation"
        content: "指令執行成功，返回了設備的完整環境狀態資訊，包括溫度感測器讀數、風扇狀態等。"
      - type: "thought"
        content: "我已經獲得了設備的環境資訊。根據 output_format，這是單一設備查詢，我需要使用單一設備格式來整理分析報告。"
    final_answer: |
      📋 **注意：這是範例模板，實際執行時必須基於工具回傳的真實資料**
      ### 重點分析
      - **狀態概況**: [基於實際 show environment all 輸出分析]
      - **關鍵數據**: [從實際工具執行結果提取]
      - **異常發現**: [基於實際檢測結果]
      ### 專業建議
      [根據實際設備狀況提供具體建議]

  - title: "直接執行示範 - 多設備狀態查詢類"
    query: "請幫我查看 {DEVICE_LIST} 這些設備的系統資訊"
    steps:
      - type: "thought"
        content: "使用者明確要求查詢系統資訊，這對應到 `show version` 指令，我不需要搜尋。這是多設備查詢，我可以直接使用 BatchCommandRunner 執行指令。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "{DEVICE_LIST}: show version"
      - type: "observation"
        content: "指令在設備上執行成功，返回了詳細的系統資訊，包括軟體版本、硬體型號、序號等。"
      - type: "thought"
        content: "我已經獲得了設備的系統資訊。根據 output_format，我需要使用適當格式來整理分析報告。"
    final_answer: |
      📋 **注意：這是範例 JSON 模板，實際執行時必須基於工具回傳的真實資料填充**
      {
        "analysis_summary": "[基於實際 BatchCommandRunner 輸出的設備狀態摘要]",
        "key_findings": [
          "[從實際 show version 輸出提取的設備資訊]",
          "[實際系統版本、硬體型號、序號資訊]"
        ],
        "anomalies": "[基於實際檢測的異常狀況]",
        "recommendations": [
          "[根據實際設備狀況的具體建議]"
        ],
        "device_count": "[實際設備數量]",
        "successful_device_count": "[從 summary 物件取得]",
        "failed_device_count": "[從 summary 物件取得]",
        "analysis_type": "[根據實際設備數量判斷]"
      }

  - title: "錯誤處理示範 - 協定狀態查詢類"
    query: "檢查 {NETWORK_DEVICES} 的路由協定狀態"
    steps:
      - type: "thought"
        content: "使用者要求檢查路由協定狀態。我需要先搜尋適當的狀態檢查指令。"
      - type: "action"
        action: "CiscoCommandSearch"
        input: "routing protocol status monitoring commands"
      - type: "observation"
        content: "搜尋結果建議使用 `show ip bgp summary` 或 `show ip route summary` 來查看路由協定狀態。"
      - type: "thought"
        content: "我找到了指令。現在對指定設備執行指令。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "{NETWORK_DEVICES}: show ip bgp summary"
      - type: "observation"
        content: "部分設備執行成功，但有設備返回錯誤，可能是因為該設備未配置該協定。"
      - type: "thought"
        content: "執行過程中遇到了部分失敗，這是正常情況。我需要根據實際結果分析，並在報告中說明失敗原因。"
    final_answer: |
      📋 **注意：這是範例 JSON 模板，實際執行時必須基於工具回傳的真實資料填充**
      {
        "analysis_summary": "[基於實際執行結果的設備協定狀態摘要]",
        "key_findings": [
          "[從實際工具輸出提取的設備狀態資訊]",
          "[實際協定配置和連接狀況]"
        ],
        "anomalies": [
          "[基於實際檢測的異常或錯誤]"
        ],
        "recommendations": [
          "[根據實際分析結果的具體建議]"
        ],
        "device_count": "[實際設備數量]",
        "successful_device_count": "[從 summary 物件取得]",
        "failed_device_count": "[從 summary 物件取得]",
        "analysis_type": "[根據實際設備數量判斷]"
      }