# Traefik v3.0 配置檔案 - AI Ops Assistant
# 企業級反向代理設定，支援 HTTP 流量路由

# =============================================================================
# 全域配置
# =============================================================================
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# =============================================================================
# API 和儀表板配置
# =============================================================================
api:
  dashboard: true
  debug: false
  insecure: true  # 開發/內網環境可使用，生產環境建議關閉

# =============================================================================
# 入口點配置 (EntryPoints)
# =============================================================================
entryPoints:
  # HTTP 入口點 - 主要流量入口
  web:
    address: ":80"
    
  # Traefik 管理面板入口點
  traefik:
    address: ":8080"

# =============================================================================
# 提供者配置 - Docker 自動發現
# =============================================================================
providers:
  # Docker 容器自動發現
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # 只有標記的容器才會被代理
    network: "ai-ops-network"  # 使用指定的 Docker 網路
    watch: true  # 即時監控容器變化
    # 限制只發現帶有特定標籤的服務，避免跨網路誤發現
    constraints: "Label(`traefik.constraint-label`,`ai-ops`)"

# =============================================================================
# 日誌配置
# =============================================================================
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# =============================================================================
# 指標和監控 (可選)
# =============================================================================
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: true

# =============================================================================
# 健康檢查
# =============================================================================
ping:
  entryPoint: "traefik"

# =============================================================================
# 憑證解析器 (預留 HTTPS 使用)
# =============================================================================
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@example.com
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         entryPoint: web