# Traefik v3.5.1 配置檔案 - 統一路由管理中心
# 企業級反向代理設定，支援多系統統一路由管理 (AI Ops + Grafana + Akvorado)

# =============================================================================
# 全域配置
# =============================================================================
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# =============================================================================
# API 和儀表板配置
# =============================================================================
api:
  dashboard: true
  debug: false
  insecure: true  # 開發/內網環境可使用，生產環境建議關閉

# =============================================================================
# 入口點配置 (EntryPoints)
# =============================================================================
entryPoints:
  # HTTP 入口點 - 主要流量入口
  web:
    address: ":80"
    
  # Grafana 專用入口點
  grafana-web:
    address: ":8003"
    
  # Traefik 管理面板入口點
  traefik:
    address: ":8080"
  
  # akvorado 公開服務入口點
  akvorado-public:
    address: ":8002"
  
  # akvorado 私有服務入口點
  akvorado-private:
    address: ":8081"

# =============================================================================
# 提供者配置 - Docker 自動發現 (統一管理三個系統)
# =============================================================================
providers:
  # Docker 容器自動發現
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # 只有標記的容器才會被代理
    watch: true  # 即時監控容器變化
    # 統一 Traefik 管理：允許跨網路發現和路由
    # 支援 ai-ops, grafana, akvorado 三個系統的統一管理
    constraints: "Label(`traefik.constraint-label`,`ai-ops`) || Label(`traefik.constraint-label`,`grafana`) || Label(`traefik.constraint-label`,`akvorado`)"
    # 預設網路：優先使用 ai-ops-network，但支援跨網路服務發現
    defaultRule: "Host(`10.60.21.11`) || Host(`202.3.184.82`)"

# =============================================================================
# 日誌配置
# =============================================================================
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# =============================================================================
# 指標和監控 (可選)
# =============================================================================
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: true

# =============================================================================
# 健康檢查
# =============================================================================
ping:
  entryPoint: "traefik"

# =============================================================================
# 憑證解析器 (預留 HTTPS 使用)
# =============================================================================
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@example.com
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         entryPoint: web