# ReAct 思考鏈範例配置
# 提供完整的思考過程範例，幫助 AI 學習正確的工作流程

react_examples:
  - title: "多指令執行模式"
    description: "當遇到多個指令時的執行模式"
    execution_pattern:
      - "分析查詢，識別所有需要執行的指令"
      - "逐一執行每個指令，不可合併"
      - "檢查執行進度，確保無遺漏"
      - "整合實際執行結果進行分析"
    critical_rules:
      - "每個指令單獨調用 BatchCommandRunner"
      - "所有數據必須來自實際執行結果"
      - "禁止使用範例中的具體數據"
      - "禁止虛構未執行指令的結果"
        
  - title: "執行完整性檢查模式"
    description: "確保不遺漏任何指令的檢查機制"
    verification_pattern:
      - "執行前：列出所有需要執行的指令"
      - "執行中：追蹤已執行和待執行的指令"
      - "執行後：確認所有指令都已完成"
      - "分析時：只使用實際獲得的數據"
    anti_patterns:
      - "❌ 跳過某個指令的執行"
      - "❌ 聲稱「無法執行」而不嘗試"
      - "❌ 基於經驗猜測結果"
      - "❌ 使用範例中的建議文字"
  - title: "搜尋型查詢 (不確定具體指令時)"
    query: "我想知道 203.0.113.20 這台設備的溫度狀況"
    steps:
      - type: "thought"
        content: "使用者想要查詢設備溫度。根據我的 Cisco 知識，我知道可以使用 `show environment all` 或 `show environment temperature` 來查看設備溫度狀態。我將使用 BatchCommandRunner 執行 `show environment all` 來獲取完整的環境資訊。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "203.0.113.20: show environment all"
      - type: "observation"
        content: "指令執行成功，返回了設備的完整環境狀態資訊，包括溫度感測器讀數、風扇狀態等。"
      - type: "thought"
        content: "我已經獲得了設備的環境資訊。根據 output_format，這是單一設備查詢，我需要使用單一設備格式來整理分析報告。"
    final_answer: |
      ### 重點分析
      - **狀態概況**: 設備環境狀態正常，所有溫度感測器讀數在正常範圍內
      - **關鍵數據**: 
        - CPU 溫度: 45°C (正常)
        - 機箱溫度: 32°C (正常)  
        - 所有風扇運作正常
      - **異常發現**: 無
      
      ### 專業建議
      建議定期監控環境狀態，確保設備在適當的運作溫度範圍內。如發現溫度異常上升，應檢查機房空調和設備通風狀況。

  - title: "直接執行型查詢 (明確指令時)"
    query: "請幫我查看 203.0.113.20 和 203.0.113.21 這兩台設備的版本資訊"
    steps:
      - type: "thought"
        content: "使用者明確要求查詢版本資訊，這對應到 `show version` 指令，我不需要搜尋。這是多設備查詢，我可以直接使用 BatchCommandRunner 執行指令。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "203.0.113.20,203.0.113.21: show version"
      - type: "observation"
        content: "指令在兩台設備上都執行成功，返回了詳細的版本資訊，包括軟體版本、硬體型號、序號等。"
      - type: "thought"
        content: "我已經獲得了兩台設備的版本資訊。根據 output_format，這是多設備查詢，我需要使用多設備格式來整理對比分析報告。"
    final_answer: |
      {
        "analysis_summary": "兩台設備版本一致且狀態良好，所有設備均運行 Cisco IOS XE 軟體",
        "key_findings": [
          "203.0.113.20: ASR1001-X, 序號 FXS1836Q2T6",
          "202.153.183.18: ASR1001-X, 序號 FXS1836Q2T7",
          "兩台設備均運行相同版本的 IOS XE 軟體"
        ],
        "anomalies": [],
        "recommendations": [
          "建議保持當前配置以維持環境一致性",
          "如需進行軟體更新，建議制定統一的更新計劃",
          "建議定期檢查軟體版本確保安全性"
        ],
        "device_count": 2,
        "successful_device_count": 2,
        "failed_device_count": 0,
        "analysis_type": "multi_device"
      }

  - title: "錯誤處理範例"
    query: "檢查設備的 BGP 狀態"
    steps:
      - type: "thought"
        content: "使用者要求檢查 BGP 狀態，但沒有指定設備。根據我的 Cisco 知識，`show ip bgp summary` 是查看 BGP 狀態摘要的標準指令。我將對所有可用設備執行此指令。"
      - type: "action"
        action: "BatchCommandRunner"
        input: "show ip bgp summary"
      - type: "observation"
        content: "部分設備執行成功，但有設備返回錯誤，可能是因為該設備未配置 BGP。"
      - type: "thought"
        content: "執行過程中遇到了部分失敗，這是正常情況。我需要根據實際結果分析，並在報告中說明失敗原因。"
    final_answer: |
      {
        "analysis_summary": "設備 BGP 配置不一致，部分設備未配置 BGP 功能",
        "key_findings": [
          "203.0.113.20: BGP 狀態正常，有 3 個鄰居連接",
          "202.153.183.18: 未配置 BGP 功能"
        ],
        "anomalies": [
          "202.153.183.18 未配置 BGP 功能，指令執行失敗"
        ],
        "recommendations": [
          "建議檢查網路架構設計，確認是否所有設備都需要配置 BGP",
          "對於需要 BGP 的設備，建議完善配置",
          "對於不需要 BGP 的設備，此錯誤可忽略",
          "建議統一網路設備的路由協定配置策略"
        ],
        "device_count": 2,
        "successful_device_count": 1,
        "failed_device_count": 1,
        "analysis_type": "multi_device"
      }

# 分析原則指導
analysis_principles:
  - title: "具體性原則"
    description: "用實際數據取代概括描述"
    example: "提供具體測量值而非'正常'、'高'等模糊詞彙"
    
  - title: "完整性原則"
    description: "系統性地涵蓋所有輸出資訊"
    example: "分析輸出的每個重要區段，不只挑選部分內容"
    
  - title: "上下文原則"
    description: "每個數據點都要包含其意義"
    example: "不只說數值，還要說明正常範圍或狀態評估"
    
  - title: "層次性原則"
    description: "從整體到細節的邏輯組織"
    example: "先總體狀況，再具體子系統，最後異常細節"

# 工作流程原則
workflow_principles:
  - "識別所有需要執行的指令"
  - "每個指令單獨調用 BatchCommandRunner"
  - "確保所有指令都已執行"
  - "只基於實際執行結果分析"
  - "絕不虛構或猜測資訊"
  - "處理部分失敗情況"

# Cisco 指令
common_cisco_commands:
  system:
    - "show version"
    - "show environment"
    - "show processes cpu"
    - "show memory"
  
  interfaces:
    - "show ip interface brief"
    - "show interface"
    - "show interface status"
  
  routing:
    - "show ip route"
    - "show ip bgp summary"
    - "show ip ospf neighbor"