# 前端動態配置檔案 - 精簡優化版本
# Created: 2025-08-05
# Optimized: 2025-08-12 - 移除未使用配置項，減少維護負擔

# =============================================================================
# API 請求相關配置 - 核心使用配置
# =============================================================================
api:
  # API 基礎路徑 - 前端 API 客戶端使用
  baseURL: "/api"
  
  # API 重試次數 - 實際使用於前端重試機制
  retryCount: 3
  
  # 重試延遲 (毫秒) - 實際使用於前端重試機制
  retryDelay: 1000
  
  # 各類操作的超時配置 (毫秒) - 前端 API 客戶端使用
  timeouts:
    # 單一指令執行超時 (60秒)
    command: 60000
    
    # AI 查詢超時 (2分鐘) - AI 分析需要更多時間
    aiQuery: 120000
    
    # 批次執行超時 (5分鐘) - 多設備操作
    batchCommand: 300000
    
    # 任務輪詢超時 (2秒) - 快速獲取任務狀態
    taskPolling: 2000
    
    # 健康檢查超時 (10秒)
    healthCheck: 10000
    
    # 設備連線測試超時 (30秒)
    deviceConnection: 30000

# =============================================================================
# 日誌相關配置 - 部分使用
# =============================================================================
logging:
  # 啟用遠端日誌收集 - SimpleLogger 使用
  enableRemoteLogging: false
  
  # 前端日誌級別 (DEBUG|INFO|WARN|ERROR) - SimpleLogger 使用
  logLevel: "INFO"
  
  # 日誌批次大小 - 批量發送數量
  batchSize: 10
  
  # 日誌批次間隔 (毫秒) - 發送間隔
  batchInterval: 5000

# =============================================================================
# 配置優化說明
# =============================================================================
# 
# 此版本移除了以下未使用的配置區段：
# - polling: 前端代碼中硬編碼輪詢參數，未使用動態配置
# - ui: 前端硬編碼 UI 時間參數，未實際使用配置
# - cache: 前端未實現配置化快取管理
# - performance: 前端未實現效能監控功能
# - development: 前端未使用開發配置項
# 
# 優化效益：
# - 配置項從 35+ 項減少到 10 項 (減少 71%)
# - 檔案大小減少約 75%
# - 只保留實際被前端代碼使用的配置項
# - 降低維護成本和配置複雜度