# 前端動態配置檔案
# 支援通過 POST /api/admin/reload-config 進行熱重載
# Created: 2025-08-05
# Version: v2.4.1

# =============================================================================
# 輪詢相關配置
# =============================================================================
polling:
  # 基礎輪詢間隔 (毫秒)
  pollInterval: 2000
  
  # 最大輪詢間隔 (毫秒) - 指數退避上限
  maxPollInterval: 10000
  
  # 總超時時間 (毫秒) - 30分鐘
  timeout: 1800000
  
  # 自動開始輪詢 - 任務創建後自動開始輪詢
  autoStartPolling: true
  
  # 指數退避倍數 - 失敗時間隔增長倍數
  backoffMultiplier: 1.2
  
  # 最大重試次數 - 連續失敗後停止輪詢
  maxRetries: 3

# =============================================================================
# UI 使用者體驗配置
# =============================================================================
ui:
  # 進度更新間隔 (毫秒) - 進度條刷新頻率
  progressUpdateInterval: 500
  
  # 錯誤訊息顯示時間 (毫秒)
  errorDisplayDuration: 5000
  
  # 成功訊息顯示時間 (毫秒)
  successDisplayDuration: 3000
  
  # 動畫持續時間 (毫秒) - UI 動畫效果
  animationDuration: 300
  
  # 防抖延遲 (毫秒) - 避免頻繁觸發操作
  debounceDelay: 300
  
  # 最大併發請求數 - 防止瀏覽器過載
  maxConcurrentRequests: 5
  
  # 自動清理輸出 - 執行完成後自動清理舊輸出
  autoCleanOutput: false
  
  # 最大輸出行數 - 超過後自動截斷
  maxOutputLines: 1000

# =============================================================================
# API 請求相關配置
# =============================================================================
api:
  # API 重試次數
  retryCount: 3
  
  # 重試延遲 (毫秒)
  retryDelay: 1000
  
  # 啟用請求去重 - v2.4.0 效能優化功能
  enableRequestDeduplication: true
  
  # 去重快取 TTL (毫秒) - 相同請求快取時間
  deduplicationTTL: 5000
  
  # 各類操作的超時配置 (毫秒)
  timeouts:
    # 單一指令執行超時 (60秒)
    command: 60000
    
    # AI 查詢超時 (2分鐘) - AI 分析需要更多時間
    aiQuery: 120000
    
    # 批次執行超時 (5分鐘) - 多設備操作
    batchCommand: 300000
    
    # 任務輪詢超時 (2秒) - 快速獲取任務狀態
    taskPolling: 2000
    
    # 健康檢查超時 (10秒)
    healthCheck: 10000
    
    # 設備連線測試超時 (30秒)
    deviceConnection: 30000

# =============================================================================
# 快取和儲存配置
# =============================================================================
cache:
  # 設備清單快取 TTL (毫秒) - 5分鐘
  deviceListTTL: 300000
  
  # 群組清單快取 TTL (毫秒) - 10分鐘
  groupListTTL: 600000
  
  # AI 狀態快取 TTL (毫秒) - 1分鐘
  aiStatusTTL: 60000
  
  # 本地儲存最大條目數
  maxLocalStorageEntries: 100
  
  # 清空快取的最大間隔 (毫秒) - 1小時
  maxCacheAge: 3600000

# =============================================================================
# 日誌相關配置
# =============================================================================
logging:
  # 啟用遠端日誌收集
  enableRemoteLogging: true
  
  # 前端日誌級別 (DEBUG|INFO|WARN|ERROR)
  logLevel: "INFO"
  
  # 日誌批次大小 - 批量發送數量
  batchSize: 10
  
  # 日誌批次間隔 (毫秒) - 發送間隔
  batchInterval: 5000
  
  # 啟用的日誌類別
  enabledCategories:
    - "api"
    - "ui"
    - "error"
    - "performance"
    - "user-action"
  
  # 單條日誌最大長度
  maxMessageLength: 1000
  
  # 啟用堆疊追蹤 - 錯誤詳細資訊
  enableStackTrace: true

# =============================================================================
# 效能監控配置
# =============================================================================
performance:
  # 啟用效能監控
  enablePerformanceMonitoring: true
  
  # 慢速請求閾值 (毫秒) - 超過記錄為慢速請求
  slowRequestThreshold: 5000
  
  # 記憶體使用監控間隔 (毫秒)
  memoryMonitoringInterval: 30000
  
  # 最大允許記憶體使用 (MB)
  maxMemoryUsage: 512
  
  # 效能資料收集間隔 (毫秒)
  metricsCollectionInterval: 60000

# =============================================================================
# 開發和除錯配置
# =============================================================================
development:
  # 啟用除錯模式 - 顯示詳細日誌
  enableDebugMode: false
  
  # 顯示 API 請求詳情
  showApiDetails: false
  
  # 模擬網路延遲 (毫秒) - 測試用途
  simulateNetworkDelay: 0
  
  # 顯示效能統計
  showPerformanceStats: false
  
  # 啟用熱重載提示
  enableHotReloadNotification: true