SIS-HD-H7A08-1:
  data:
    description: HD SIS設備
    device_config:
      description: HD SIS設備
      device_type: cisco_xe
      ip: 202.153.183.18
      model: Cisco ASR 1001-X
      name: SIS-HD-H7A08-1
      os: cisco_xe
      password: mbfg2017
      username: admin
    model: Cisco ASR 1001-X
  groups:
  - cisco_xe_devices
  hostname: 202.153.183.18
  password: mbfg2017
  platform: cisco_xe
  username: admin
SIS-LY-C0609:
  data:
    description: LY SIS設備
    device_config:
      description: LY SIS設備
      device_type: cisco_xe
      ip: 202.3.182.202
      model: Cisco ASR 1001-X
      name: SIS-LY-C0609
      os: cisco_xe
      password: mbfg2017
      username: admin
    model: Cisco ASR 1001-X
  groups:
  - cisco_xe_devices
  hostname: 202.3.182.202
  password: mbfg2017
  platform: cisco_xe
  username: admin
